import {
  PiDress,
  PiTelevision,
  PiSoccerBall,
  PiPinwheel,
  PiDog,
  PiCar,
  PiBaby,
  PiLifebuoy,
  PiFirstAid,
  PiHandSoap,
  PiHouseLine,
} from "react-icons/pi";

export const niches = [
  { name: { en: "Fashion", fr: "" }, icon: <PiDress />, id: "fashion" },
  { name: { en: "Beauty and Personal Care", fr: "" }, icon: <PiHandSoap />, id: "beauty-and-personal-care", },
  { name: { en: "Home", fr: "" }, icon: <PiHouseLine />, id: "home" },
  { name: { en: "Electronics and gadgets", fr: "" }, icon: <PiTelevision />, id: "electronics-and-gadgets", },
  { name: { en: "Health and Wellness", fr: "" }, icon: <PiFirstAid />, id: "health-and-wellness", },
  { name: { en: "Sports and Outdoors", fr: "" }, icon: <PiSoccerBall />, id: "sports-and-outdoors", },
  { name: { en: "Toys and Games", fr: "" }, icon: <PiPinwheel />, id: "toys-and-games", },
  { name: { en: "Pets", fr: "" }, icon: <PiDog />, id: "pets" },
  { name: { en: "Automotive", fr: "" }, icon: <PiCar />, id: "automotive" },
  { name: { en: "Baby and Toddler", fr: "" }, icon: <PiBaby />, id: "baby-and-toddler", },
  { name: { en: "Lifestyle and culture", fr: "" }, icon: <PiLifebuoy />, id: "lifestyle-and-culture", },
];

export const subNiches = [
  { parentId: "fashion", id: "clothing", text: { en: "Clothing", fr: "" }, subText: { en: "Lorem ipsum dolor sit amet consectetur. Aliquam neque amet elit diam et.", fr: "" }, icon: "" },
  { parentId: "fashion", id: "shoes", text: { en: "Shoes", fr: "" }, subText: { en: "Lorem ipsum dolor sit amet consectetur. Aliquam neque amet elit diam et.", fr: "" }, icon: "" },
  { parentId: "fashion", id: "jewelry", text: { en: "Jewelry", fr: "" }, subText: { en: "Lorem ipsum dolor sit amet consectetur. Aliquam neque amet elit diam et.", fr: "" }, icon: "" },
  { parentId: "beauty-and-personal-care", id: "makeup", text: { en: "Makeup", fr: "" }, subText: { en: "Lorem ipsum dolor sit amet consectetur. Aliquam neque amet elit diam et.", fr: "" }, icon: "" },
  { parentId: "beauty-and-personal-care", id: "cosmetics", text: { en: "Cosmetics", fr: "" }, subText: { en: "Lorem ipsum dolor sit amet consectetur. Aliquam neque amet elit diam et.", fr: "" }, icon: "" },
  { parentId: "beauty-and-personal-care", id: "skin-care", text: { en: "Skin care", fr: "" }, subText: { en: "Lorem ipsum dolor sit amet consectetur. Aliquam neque amet elit diam et.", fr: "" }, icon: "" },
  { parentId: "beauty-and-personal-care", id: "hair-care", text: { en: "Hair care", fr: "" }, subText: { en: "Lorem ipsum dolor sit amet consectetur. Aliquam neque amet elit diam et.", fr: "" }, icon: "" },
  { parentId: "beauty-and-personal-care", id: "fragrances", text: { en: "Fragrances", fr: "" }, subText: { en: "Lorem ipsum dolor sit amet consectetur. Aliquam neque amet elit diam et.", fr: "" }, icon: "" },
  { parentId: "home", id: "furniture", text: { en: "Furniture", fr: "" }, subText: { en: "Lorem ipsum dolor sit amet consectetur. Aliquam neque amet elit diam et.", fr: "" }, icon: "" },
  { parentId: "home", id: "home-decor", text: { en: "Home Decor", fr: "" }, subText: { en: "Lorem ipsum dolor sit amet consectetur. Aliquam neque amet elit diam et.", fr: "" }, icon: "" },
  { parentId: "home", id: "kitchen", text: { en: "Kitchen", fr: "" }, subText: { en: "Lorem ipsum dolor sit amet consectetur. Aliquam neque amet elit diam et.", fr: "" }, icon: "" },
  { parentId: "home", id: "garden", text: { en: "Garden", fr: "" }, subText: { en: "Lorem ipsum dolor sit amet consectetur. Aliquam neque amet elit diam et.", fr: "" }, icon: "" },
  { parentId: "electronics-and-gadgets", id: "consumer-electronics", text: { en: "Consumer electronics", fr: "" }, subText: { en: "Lorem ipsum dolor sit amet consectetur. Aliquam neque amet elit diam et.", fr: "" }, icon: "", }, 
  { parentId: "electronics-and-gadgets", id: "wearable-technology", text: { en: "Wearable Technology", fr: "" }, subText: { en: "Lorem ipsum dolor sit amet consectetur. Aliquam neque amet elit diam et.", fr: "" }, icon: "", }, 
  { parentId: "electronics-and-gadgets", id: "phone-accessories", text: { en: "Phone accessories", fr: "" }, subText: { en: "Lorem ipsum dolor sit amet consectetur. Aliquam neque amet elit diam et.", fr: "" }, icon: "", }, 
  { parentId: "electronics-and-gadgets", id: "audio-and-headphones", text: { en: "Audio and Headphones", fr: "" }, subText: { en: "Lorem ipsum dolor sit amet consectetur. Aliquam neque amet elit diam et.", fr: "" }, icon: "", }, 
  { parentId:"health-and-wellness", id: "fitness-and-exercise", text: { en: "Fitness and exercise", fr: "" }, subText: { en: "Lorem ipsum dolor sit amet consectetur. Aliquam neque amet elit diam et.", fr: "" }, icon: "", }, 
  { parentId:"health-and-wellness", id: "sleep", text: { en: "Sleep", fr: "" }, subText: { en: "Lorem ipsum dolor sit amet consectetur. Aliquam neque amet elit diam et.", fr: "" }, icon: "" },
  { parentId:"health-and-wellness", id: "personal-care", text: { en: "Personal Care", fr: "" }, subText: { en: "Lorem ipsum dolor sit amet consectetur. Aliquam neque amet elit diam et.", fr: "" }, icon: "" },
  { parentId:"health-and-wellness", id: "vitamins-and-supplements", text: { en: "Vitamins and supplements", fr: "" }, subText: { en: "Lorem ipsum dolor sit amet consectetur. Aliquam neque amet elit diam et.", fr: "" }, icon: "", }, 
  { parentId:"health-and-wellness", id: "nutrition", text: { en: "Nutrition", fr: "" }, subText: { en: "Lorem ipsum dolor sit amet consectetur. Aliquam neque amet elit diam et.", fr: "" }, icon: "" },
  { parentId:"health-and-wellness", id: "mental-health", text: { en: "Mental Health", fr: "" }, subText: { en: "Lorem ipsum dolor sit amet consectetur. Aliquam neque amet elit diam et.", fr: "" }, icon: "" },
  { parentId:"health-and-wellness", id: "diets", text: { en: "Diets", fr: "" }, subText: { en: "Lorem ipsum dolor sit amet consectetur. Aliquam neque amet elit diam et.", fr: "" }, icon: "" },
  { parentId:"health-and-wellness", id: "healthcare ", text: { en: "Healthcare ", fr: "" }, subText: { en: "Lorem ipsum dolor sit amet consectetur. Aliquam neque amet elit diam et.", fr: "" }, icon: "" },
  { parentId: "sports-and-outdoors", id: "sporting-goods", text: { en: "Sporting Goods", fr: "" }, subText: { en: "Lorem ipsum dolor sit amet consectetur. Aliquam neque amet elit diam et.", fr: "" }, icon: "" },
  { parentId: "sports-and-outdoors", id: "outdoor-gear", text: { en: "Outdoor gear", fr: "" }, subText: { en: "Lorem ipsum dolor sit amet consectetur. Aliquam neque amet elit diam et.", fr: "" }, icon: "" },
  { parentId: "sports-and-outdoors", id: "camping-and-hiking", text: { en: "Camping and hiking", fr: "" }, subText: { en: "Lorem ipsum dolor sit amet consectetur. Aliquam neque amet elit diam et.", fr: "" }, icon: "", }, 
  { parentId: "sports-and-outdoors", id: "athletic-apparel-and-footwear", text: { en: "Athletic apparel and footwear", fr: "" }, subText: { en: "Lorem ipsum dolor sit amet consectetur. Aliquam neque amet elit diam et.", fr: "" }, icon: "", }, 
  { parentId: "sports-and-outdoors", id: "biking-accessories", text: { en: "Biking accessories", fr: "" }, subText: { en: "Lorem ipsum dolor sit amet consectetur. Aliquam neque amet elit diam et.", fr: "" }, icon: "", }, 
  { parentId: "toys-and-games", id: "educational-toys", text: { en: "Educational Toys", fr: "" }, subText: { en: "Lorem ipsum dolor sit amet consectetur. Aliquam neque amet elit diam et.", fr: "" }, icon: "", }, 
  { parentId: "toys-and-games", id: "board-games", text: { en: "Board Games", fr: "" }, subText: { en: "Lorem ipsum dolor sit amet consectetur. Aliquam neque amet elit diam et.", fr: "" }, icon: "" },
  { parentId: "toys-and-games", id: "outdoor-play-equipment", text: { en: "Outdoor Play equipment", fr: "" }, subText: { en: "Lorem ipsum dolor sit amet consectetur. Aliquam neque amet elit diam et.", fr: "" }, icon: "", }, 
  { parentId: "toys-and-games", id: "remote-controlled-toys", text: { en: "Remote controlled toys", fr: "" }, subText: { en: "Lorem ipsum dolor sit amet consectetur. Aliquam neque amet elit diam et.", fr: "" }, icon: "", }, 
  { parentId: "toys-and-games", id: "gaming", text: { en: "Gaming", fr: "" }, subText: { en: "Lorem ipsum dolor sit amet consectetur. Aliquam neque amet elit diam et.", fr: "" }, icon: "" },
  { parentId: "pets", id: "pet-toys", text: { en: "Pet toys", fr: "" }, subText: { en: "Lorem ipsum dolor sit amet consectetur. Aliquam neque amet elit diam et.", fr: "" }, icon: "" },
  { parentId: "pets", id: "pet-accessories", text: { en: "Pet accessories", fr: "" }, subText: { en: "Lorem ipsum dolor sit amet consectetur. Aliquam neque amet elit diam et.", fr: "" }, icon: "", }, 
  { parentId: "pets", id: "pet-grooming", text: { en: "Pet grooming", fr: "" }, subText: { en: "Lorem ipsum dolor sit amet consectetur. Aliquam neque amet elit diam et.", fr: "" }, icon: "" },
  { parentId: "pets", id: "pet-healthcare", text: { en: "Pet healthcare", fr: "" }, subText: { en: "Lorem ipsum dolor sit amet consectetur. Aliquam neque amet elit diam et.", fr: "" }, icon: "" },
  { parentId: "automotive", id: "car-accessories", text: { en: "Car accessories", fr: "" }, subText: { en: "Lorem ipsum dolor sit amet consectetur. Aliquam neque amet elit diam et.", fr: "" }, icon: "", }, 
  { parentId: "automotive", id: "car-care", text: { en: "Car care", fr: "" }, subText: { en: "Lorem ipsum dolor sit amet consectetur. Aliquam neque amet elit diam et.", fr: "" }, icon: "" },
  { parentId: "automotive", id: "Electronics", text: { en: "Electronics", fr: "" }, subText: { en: "Lorem ipsum dolor sit amet consectetur. Aliquam neque amet elit diam et.", fr: "" }, icon: "" },
  { parentId: "baby-and-toddler", id: "Clothes", text: { en: "Clothes", fr: "" }, subText: { en: "Lorem ipsum dolor sit amet consectetur. Aliquam neque amet elit diam et.", fr: "" }, icon: "" },
  { parentId: "baby-and-toddler", id: "Security", text: { en: "Security", fr: "" }, subText: { en: "Lorem ipsum dolor sit amet consectetur. Aliquam neque amet elit diam et.", fr: "" }, icon: "" },
  { parentId: "baby-and-toddler", id: "babys-room", text: { en: "Baby`s Room", fr: "" }, subText: { en: "Lorem ipsum dolor sit amet consectetur. Aliquam neque amet elit diam et.", fr: "" }, icon: "" },
  { parentId: "baby-and-toddler", id: "car-seats-and-accessories", text: { en: "Car seats and accessories", fr: "" }, subText: { en: "Lorem ipsum dolor sit amet consectetur. Aliquam neque amet elit diam et.", fr: "" }, icon: "", }, 
  { parentId: "baby-and-toddler", id: "toys", text: { en: "Toys", fr: "" }, subText: { en: "Lorem ipsum dolor sit amet consectetur. Aliquam neque amet elit diam et.", fr: "" }, icon: "" },
  { parentId: "lifestyle-and-culture", id: "travel", text: { en: "Travel", fr: "" }, subText: { en: "Lorem ipsum dolor sit amet consectetur. Aliquam neque amet elit diam et.", fr: "" }, icon: "" },
  { parentId: "lifestyle-and-culture", id: "education", text: { en: "Education", fr: "" }, subText: { en: "Lorem ipsum dolor sit amet consectetur. Aliquam neque amet elit diam et.", fr: "" }, icon: "" },
  { parentId: "lifestyle-and-culture", id: "art", text: { en: "Art", fr: "" }, subText: { en: "Lorem ipsum dolor sit amet consectetur. Aliquam neque amet elit diam et.", fr: "" }, icon: "" },
];
