export const nicheIcons = [
  { id: 11, name: "Home Decor", icon: "/assets/icons/PaintRoller.png" },
  { id: 269, name: "Garden", icon: "/assets/icons/PottedPlant.png" },
  { id: 270, name: "Furniture", icon: "/assets/icons/Couch.png" },
  { id: 951, name: "Kitchen", icon: "/assets/icons/kitchen.png" },
  { id: 403, name: "Security", icon: "/assets/icons/baby room.png" },
  { id: 432, name: "Toys", icon: "/assets/icons/toys.png" },
  { id: 985, name: "Clothes", icon: "/assets/icons/TShirt.png" },
  { id: 124, name: "Jewelry", icon: "/assets/icons/jewelry.png" },
  { id: 18, name: "Clothing", icon: "/assets/icons/Dress.png" },
  { id: 697, name: "Shoes", icon: "/assets/icons/Sneaker.png" },
  {
    id: 1191,
    name: "Biking Accessories",
    icon: "/assets/icons/Bicycle.png",
  },
  { id: 263, name: "Sporting Goods", icon: "/assets/icons/Basketball.png" },
  { id: 542, name: "Camping and Hiking", icon: "/assets/icons/Tent.png" },
  // { id: 688, name: "Outdoor Gear", icon: "/assets/icons/Backpack.png" },
  { id: 983, name: "Athletic Apparel", icon: "/assets/icons/Hoodie.png" },
  {
    id: 432,
    name: "Remote Controlled Toys",
    icon: "/assets/icons/remote controlled toys.png",
  },
  { id: 8, name: "Gaming", icon: "/assets/icons/GameController.png" },
  { id: 920, name: "Board Games", icon: "/assets/icons/PuzzlePiece.png" },
  { id: 146, name: "Hair care", icon: "/assets/icons/hair care.png" },
  { id: 234, name: "Makeup & Cosmetics", icon: "/assets/icons/makeup.png" },
  { id: 242, name: "Fragrances", icon: "/assets/icons/frangraces.png" },
  { id: 44, name: "Skin care", icon: "/assets/icons/skin care.png" },
  { id: 45, name: "Personal Care", icon: "/assets/icons/HandSoap.png" },
  {
    id: 237,
    name: "Vitamins and Supplements",
    icon: "/assets/icons/Pill.png",
  },
  { id: 419, name: "Healthcare", icon: "/assets/icons/HandHeart.png" },
  {
    id: 437,
    name: "Mental Health",
    icon: "/assets/icons/mental health.png",
  },
  { id: 456, name: "Nutrition", icon: "/assets/icons/Pill.png" },
  { id: 457, name: "Diets", icon: "/assets/icons/diet.png" },
  { id: 0, name: "Sleep", icon: "/assets/icons/sleep.png" },
  {
    id: 94,
    name: "Fitness and Exercise",
    icon: "/assets/icons/Barbell.png",
  },
  { id: 1188, name: "Car Electronics", icon: "/assets/icons/Radio.png" },
  { id: 138, name: "Car care", icon: "/assets/icons/Toolbox.png" },
  {
    id: 47,
    name: "Car Accessories",
    icon: "/assets/icons/baby car seat.png",
  },
  {
    id: 1171,
    name: "Phone Accessories",
    icon: "/assets/icons/PlugCharging.png",
  },
  {
    id: 361,
    name: "Audio and Headphones",
    icon: "/assets/icons/Headset.png",
  },
  {
    id: 78,
    name: "Consumer Electronics",
    icon: "/assets/icons/Television.png",
  },
  {
    id: 66,
    name: "Pet Accessories",
    icon: "/assets/icons/pet accessories.png",
  },
  {
    id: 380,
    name: "Pet healthcare",
    icon: "/assets/icons/pet healthcare.png",
  },
  { id: 203, name: "Travel", icon: "/assets/icons/Airplane.png" },
  { id: 74, name: "Education", icon: "/assets/icons/GraduationCap.png" },
  { id: 3, name: "Art", icon: "/assets/icons/Palette.png" },

  { id: 432, name: "Pet Toys", icon: "/assets/icons/pet toys.png" },
  { id: 883, name: "Pet Grooming", icon: "/assets/icons/pet grooming.png" },
  { id: 157, name: "Human resources", icon: "/assets/icons/Headset.png" },
  { id: 75, name: "Legal", icon: "/assets/icons/GraduationCap.png" },
  { id: 25, name: "Marketing", icon: "/assets/icons/Radio.png" },
  { id: 67, name: "Travel", icon: "/assets/icons/baby security.png" },
  {
    id: 29,
    name: "Real estate",
    icon: "/assets/icons/outdoor play equipment.png",
  },
  { id: 841, name: "Retail", icon: "/assets/icons/TShirt.png" },
  { id: 703, name: "Workplace", icon: "/assets/icons/Toolbox.png" },
  { id: 801, name: "Supply chain", icon: "/assets/icons/educational toys.png" },

  { id: 277, name: "Alcohol", icon: "/assets/icons/pet healthcare.png" },
  { id: 560, name: "Beverages", icon: "/assets/icons/beverage.png" },
  { id: 122, name: "Cooking", icon: "/assets/icons/kitchen.png" },
  { id: 1150, name: "Cpg", icon: "/assets/icons/PuzzlePiece.png" },
  { id: 71, name: "Food", icon: "/assets/icons/Carrot.png" },
  { id: 121, name: "Grocery", icon: "/assets/icons/diet.png" },

  { id: 1343, name: "Gaming", icon: "/assets/icons/GameController.png" },
  { id: 613, name: "Media", icon: "/assets/icons/Television.png" },
  { id: 688, name: "Sports And Outdoor", icon: "/assets/icons/Basketball.png" },
  { id: 220, name: "Streaming", icon: "/assets/icons/screen.png" },
  { id: 431, name: "Toys And Games", icon: "/assets/icons/remote controlled toys.png" },
];

export const categoryIcons = [
  { id: 0, icon: "/assets/icons/makeup.png" },
  { id: 1, icon: "/assets/icons/Dress.png" },
  { id: 2, icon: "/assets/icons/Couch.png" },
  { id: 3, icon: "/assets/icons/HandHeart.png" },
  { id: 4, icon: "/assets/icons/Airplane.png" },
  { id: 5, icon: "/assets/icons/Toolbox.png" },
  { id: 6, icon: "/assets/icons/Carrot.png" },
  { id: 7, icon: "/assets/icons/Television.png" },
];
