export const niches = [
  { category: "home", id: 137, name: "Home Decor", value: "home-decor" },
  { category: "home", id: 269, name: "Garden", value: "garden" },
  { category: "home", id: 270, name: "Furniture", value: "furniture" },
  { category: "home", id: 951, name: "Kitchen", value: "kitchen" },
  {
    category: "baby-and-toddler",
    id: 403,
    name: "Security",
    value: "security",
  },
  { category: "baby-and-toddler", id: 432, name: "Toys", value: "toys" },
  { category: "baby-and-toddler", id: 985, name: "Clothes", value: "clothes" },
  { category: "fashion", id: 350, name: "Jewelry", value: "jewelry" },
  { category: "fashion", id: 68, name: "Clothing", value: "clothing" },
  { category: "fashion", id: 697, name: "Shoes", value: "shoes" },
  {
    category: "sports-and-outdoors",
    id: 1191,
    name: "Biking Accessories",
    value: "biking-accessories",
  },
  {
    category: "sports-and-outdoors",
    id: 263,
    name: "Sporting Goods",
    value: "sporting-goods",
  },
  {
    category: "sports-and-outdoors",
    id: 542,
    name: "Camping and Hiking",
    value: "camping-and-hiking",
  },
  {
    category: "sports-and-outdoors",
    id: 688,
    name: "Outdoor Gear",
    value: "outdoor-gear",
  },
  {
    category: "sports-and-outdoors",
    id: 983,
    name: "Athletic Apparel",
    value: "athletic-apparel",
  },
  {
    category: "toys-and-games",
    id: 432,
    name: "Remote Controlled Toys",
    value: "remote-controlled-toys",
  },
  { category: "toys-and-games", id: 8, name: "Gaming", value: "gaming" },
  {
    category: "toys-and-games",
    id: 920,
    name: "Board Games",
    value: "board-games",
  },
  {
    category: "beauty-and-personal-care",
    id: 146,
    name: "Hair care",
    value: "hair-care",
  },
  {
    category: "beauty-and-personal-care",
    id: 234,
    name: "Makeup & Cosmetics",
    value: "makeup-&-cosmetics",
  },
  {
    category: "beauty-and-personal-care",
    id: 242,
    name: "Fragrances",
    value: "fragrances",
  },
  {
    category: "beauty-and-personal-care",
    id: 93,
    name: "Skin care",
    value: "skin-care",
  },
  {
    category: "health-and-wellness",
    id: 143,
    name: "Personal Care",
    value: "personal-care",
  },
  {
    category: "health-and-wellness",
    id: 237,
    name: "Vitamins and Supplements",
    value: "vitamins-and-supplements",
  },
  {
    category: "health-and-wellness",
    id: 419,
    name: "Healthcare",
    value: "healthcare",
  },
  {
    category: "health-and-wellness",
    id: 437,
    name: "Mental Health",
    value: "mental-health",
  },
  {
    category: "health-and-wellness",
    id: 456,
    name: "Nutrition",
    value: "nutrition",
  },
  { category: "health-and-wellness", id: 457, name: "Diets", value: "diets" },
  { category: "health-and-wellness", id: 633, name: "Sleep", value: "sleep" },
  {
    category: "health-and-wellness",
    id: 94,
    name: "Fitness and Exercise",
    value: "fitness-and-exercise",
  },
  {
    category: "automotive",
    id: 1188,
    name: "Car Electronics",
    value: "car-electronics",
  },
  { category: "automotive", id: 138, name: "Car care", value: "car-care" },
  {
    category: "automotive",
    id: 89,
    name: "Car Accessories",
    value: "car-accessories",
  },
  {
    category: "electronics-and-gadgets",
    id: 1171,
    name: "Phone Accessories",
    value: "phone-accessories",
  },
  {
    category: "electronics-and-gadgets",
    id: 361,
    name: "Audio and Headphones",
    value: "audio-and-headphones",
  },
  {
    category: "electronics-and-gadgets",
    id: 78,
    name: "Consumer Electronics",
    value: "consumer-electronics",
  },
  {
    category: "pets",
    id: 379,
    name: "Pet Accessories",
    value: "pet-accessories",
  },
  {
    category: "pets",
    id: 380,
    name: "Pet healthcare",
    value: "pet-healthcare",
  },
  { category: "pets", id: 432, name: "Pet Toys", value: "pet-toys" },
  { category: "pets", id: 883, name: "Pet Grooming", value: "pet-grooming" },
  {
    category: "lifestyle-and-culture",
    id: 1011,
    name: "Education",
    value: "education",
  },
  { category: "lifestyle-and-culture", id: 24, name: "Art", value: "art" },
  {
    category: "lifestyle-and-culture",
    id: 67,
    name: "Travel",
    value: "travel",
  },
];
