import {
  PiDress,
  PiTelevision,
  PiSoccerBall,
  PiPinwheel,
  PiDog,
  PiCar,
  PiBaby,
  PiLifebuoy,
  PiFirstAid,
  PiHandSoap,
  PiHouseLine,
} from "react-icons/pi";

export const niches = [
  {
    name: "Fashion",
    icon: <PiDress />,
    id: "fashion",
    items: ["Clothing", "Shoes", "Jewelry"],
  },
  {
    name: "Beauty and Personal Care",
    icon: <PiHandSoap />,
    id: "beauty-and-personal-care",
    items: ["Makeup", "Cosmetics", "Skin care", "Hair care", "Fragrances"],
  },
  {
    name: "Home",
    icon: <PiHouseLine />,
    id: "home",
    items: ["Furniture", "Home Decor", "Kitchen", "Garden"],
  },
  {
    name: "Electronics and gadgets",
    icon: <PiTelevision />,
    id: "electronics-and-gadgets",
    items: [
      "Consumer electronics",
      "Wearable Technology",
      "Phone accessories",
      "Audio and Headphones",
    ],
  },
  {
    name: "Health and Wellness",
    icon: <PiFirstAid />,
    id: "health-and-wellness",
    items: [
      "Fitness and exercise",
      "Sleep",
      "Personal Care",
      "Vitamins and supplements",
      "Nutrition",
      "Mental Health",
      "Diets",
      "Healthcare ",
    ],
  },
  {
    name: "Sports and Outdoors",
    icon: <PiSoccerBall />,
    id: "sports-and-outdoors",
    items: [
      "Sporting Goods",
      "Outdoor gear",
      "Camping and hiking",
      "Athletic apparel and footwear",
      "Biking accessories",
    ],
  },
  {
    name: "Toys and Games",
    icon: <PiPinwheel />,
    id: "toys-and-games",
    items: [
      "Educational Toys",
      "Board Games",
      "Outdoor Play equipment",
      "Remote controlled toys",
      "Gaming",
    ],
  },
  {
    name: "Pets",
    icon: <PiDog />,
    id: "pets",
    items: ["Pet toys", "Pet accessories", "Pet grooming", "Pet healthcare"],
  },
  {
    name: "Automotive",
    icon: <PiCar />,
    id: "automotive",
    items: ["Car accessories", "Car care", "Electronics"],
  },
  {
    name: "Baby and Toddler",
    icon: <PiBaby />,
    id: "baby-and-toddler",
    items: [
      "Clothes",
      "Security",
      "Baby`s Room",
      "Car seats and accessories",
      "Toys",
    ],
  },
  {
    name: "Lifestyle and culture",
    icon: <PiLifebuoy />,
    id: "lifestyle-and-culture",
    items: ["Travel", "Education", "Art"],
  },
];
